defaults:
  - emoji: ":spiral_calendar_pad:"
    text: "In a meeting"
  - emoji: ":bus:"
    text: "Commuting"
  - emoji: ":face_with_thermometer:"
    text: "Out sick"
  - emoji: ":palm_tree:"
    text: "Vacationing"
  - emoji: ":house:"
    text: "Working remotely"
  - emoji: ":no_entry:"
    text: "Out of office"
integrations:
- app: "Outlook Calendar"
- app: "Google Calendar" 
group_ids:
  - "S09FVUZRWUT"
