defaults:
  - emoji: ":spiral_calendar_pad:"
  - emoji: ":bus:"
  - emoji: ":face_with_thermometer:"
  - emoji: ":palm_tree:"
  - emoji: ":house:"
  - emoji: ":no_entry:"
group_ids:
  - "S09FVUZRWUT"
